options:
  logs_bucket: gs://cimon-bucket  # bucket name

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cimon-image:latest', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cimon-image:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 
      'deploy', 
      'cimon-app', 
      '--image', 
      'gcr.io/$PROJECT_ID/cimon-image:latest', 
      '--region', 
      'asia-southeast2', 
      '--platform', 
      'managed', 
      '--allow-unauthenticated'
    ]

images: 
  - 'gcr.io/$PROJECT_ID/cimon-image'
