steps:
# build the container image
- name   : 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cimon-image:latest', '.']
# push the container image to container registry
- name : 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cimon-image:latest']
# deploy container imageto Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'cimon-app', '--image', 'gcr.io/$PROJECT_ID/cimon-image:latest', '--region', 'asia-southeast2', '--platform', 'managed, '--allow-all-unauthanticated']
images: 
  -gcr.io/$PROJECT_ID/cimon-image