steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_AR_HOSTNAME/$_PROJECT_ID/$_REPO_NAME/cimon-image:latest'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_AR_HOSTNAME/$_PROJECT_ID/$_REPO_NAME/cimon-image:latest'
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - '$_SERVICE_NAME'
      - '--image'
      - '$_AR_HOSTNAME/$_PROJECT_ID/$_REPO_NAME/cimon-image:latest'
      - '--region'
      - '$_DEPLOY_REGION'
      - '--platform'
      - '$_PLATFORM'
      - '--allow-unauthenticated'
      - '--port'
      - '9000'  # Specify the port here
timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY
