steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_AR_HOSTNAME/$_PROJECT_ID/$_REPO_NAME:latest'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_AR_HOSTNAME/$_PROJECT_ID/$_REPO_NAME:latest'
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - '$_SERVICE_NAME'
      - '--image'
      - '$_AR_HOSTNAME/$_PROJECT_ID/$_REPO_NAME:latest'
      - '--region'
      - '$_DEPLOY_REGION'
      - '--platform'
      - '$_PLATFORM'
      - '--allow-unauthenticated'
timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY
