steps:
  # Build the image
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "-t", "gcr.io/chili-monitoring-2024/cimon-image:${SHORT_SHA}",
      "."
    ]

  # Push the image
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "push",
      "gcr.io/chili-monitoring-2024/cimon-image:${SHORT_SHA}"
    ]

  # Access the secret and store it as a file
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: "bash"
  args:
  - "-c"
  - |
    # Download the service.json secret from Secret Manager
    gcloud secrets versions access latest --secret=firebase-service-account > /workspace/service.json
    ls -l /workspace/  # List the files in the /workspace directory


  # Deploy the service
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      "run",
      "deploy",
      "cimon-web-service",
      "--image",
      "gcr.io/chili-monitoring-2024/cimon-image:${SHORT_SHA}",
      "--region",
      "asia-southeast2",
      "--platform", 
      "managed",
      "--allow-unauthenticated",
      "--port", 
      "9002",
      "--set-env-vars",
      "GOOGLE_APPLICATION_CREDENTIALS=/workspace/service.json"
    ]

timeout: 3600s
options:
  logging: CLOUD_LOGGING_ONLY
