steps:
  # Build the image
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "-t", "gcr.io/${_PROJECT_ID}/cimon-image:${_VERSION}",
      "."
    ]

  # Push the image
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "push",
      "gcr.io/${_PROJECT_ID}/cimon-image:${_VERSION}"
    ]

  # Deploy the service
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      "run",
      "deploy",
      "${_SERVICE_NAME}",
      "--image",
      "gcr.io/${_PROJECT_ID}/cimon-image:${_VERSION}",
      "--region",
      "${_DEPLOY_REGION}",
      "--platform", 
      "${_PLATFORM}",
      "--allow-unauthenticated",
      "--port", 
      "9001"
    ]

timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY
subtitutions:
  "_VERSION": "1.0"

