name: CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Build the image
      - name: Build Docker Image
        run: |
          docker build -t cimon-image .

      # Tag the image
      - name: Tag Docker Image
        run: |
          docker tag cimon-image gcr.io/chili-monitoring-2024/cimon-image:${GITHUB_SHA::7}

      # Push the image
      - name: Push Docker Image
        run: |
          docker push gcr.io/chili-monitoring-2024/cimon-image:${GITHUB_SHA::7}

      # Deploy the service
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cimon-web-service \
            --image gcr.io/chili-monitoring-2024/cimon-image:${GITHUB_SHA::7} \
            --region asia-southeast2 \
            --platform managed \
            --allow-unauthenticated \
            --port 9002 